# Generated by Django 5.0.4 on 2024-04-11 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=9)),
                ("email", models.EmailField(max_length=50)),
                (
                    "role",
                    models.IntegerField(
                        choices=[
                            (0, "inactive"),
                            (1, "customer"),
                            (2, "employee"),
                            (3, "admin"),
                        ],
                        default=0,
                    ),
                ),
                ("password", models.CharField(max_length=20)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.department",
                    ),
                ),
            ],
        ),
    ]
